---
language: python
python: "2.7"
dist: trusty
sudo: false
group: beta
services: [docker]
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

install:
  - pip install -r tests/requirements.txt | cat
  - ansible-galaxy install git+file://$(pwd),$(git rev-parse --abbrev-ref HEAD) -p .molecule/roles
  - molecule dependency
  - for version in 14.07 15.05; do docker pull xdrum/openwrt:$version; done

script:
  - pre-commit run --all-files
  - molecule test --driver docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
