---
# tasks file for openwrt-bootstrap

- name: Update opkg package lists
  raw: opkg update
  changed_when: False

- name: opkg install python
  raw: opkg install python
  register: openwrt_bootstrap_install_python
  changed_when: "'Downloading' in openwrt_bootstrap_install_python.stdout"

- name: opkg install ip
  opkg:
      name: ip
      state: present
